name: bloat
on: [push, pull_request]
jobs:
  bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo install cargo-bloat
      - run: cargo bloat --release --crates --all-features -- -threshold=5
