on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --verbose
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
      - run: git diff --exit-code