name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy, rustfmt, bloat
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - run: cargo fmt --all -- --check
    - run: cargo clippy --all-features -- -D warnings
    - run: cargo build --verbose
    - run: cargo test --verbose
    - run: cargo bloat --release --crates --all-features -- -threshold=5
